#!/bin/bash

BOOTSTRAP_DIR="bootstrap"
BOOTSTRAP_LESS_DIR="$BOOTSTRAP_DIR/less"
BOOTSTRAP_JS_DIR="$BOOTSTRAP_DIR/js"
BOOTSTRAP_FONT_DIR="$BOOTSTRAP_DIR/fonts"
PACKAGE_JS="package.js"

if [ ! -d $BOOTSTRAP_DIR ]
then
  echo "You should run 'git submodule update' before running this"
fi

LESS_FILES=`find $BOOTSTRAP_LESS_DIR -name "*.less"`
JS_FILES=`find $BOOTSTRAP_JS_DIR -name "*.js" -a ! -path '*tests*'`
FONT_FILES="$BOOTSTRAP_DIR/fonts/*"

# remove everything after the token
sed -i '' '/AUTOGENERATED/,$d' $PACKAGE_JS
echo "  // AUTOGENERATED" >> $PACKAGE_JS

# add all js and less files
echo "  api.add_files([" >> $PACKAGE_JS
for FILE in $LESS_FILES $JS_FILES
do
  echo "    '$FILE'," >> $PACKAGE_JS
done
echo "  ], 'server', {isAsset:true});" >> $PACKAGE_JS

# add fonts directly for the frontend
echo "  api.add_files([" >> $PACKAGE_JS
for FILE in $FONT_FILES
do
  echo "    '$FILE'," >> $PACKAGE_JS
done
echo "  ], 'client');" >> $PACKAGE_JS

# end the use statement
echo "});" >> $PACKAGE_JS
